######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 24 21:51:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src/

DEFINES += TEST_GOOGLE_CONTACTS

QT += testlib
LIBS += -Wl,-rpath,../../lib -L../../lib -lTHGoogle

# Input
HEADERS += contactstest.h
SOURCES += contactstest.cpp
