######################################################################
# Automatically generated by qmake (2.01a) Fri May 1 19:49:51 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += /home/qtdev/Qt/JSON/. . src

# Input
HEADERS += src/jsonstreamreader.h
SOURCES += src/jsonstreamreader.cpp src/main.cpp
