######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 5 09:00:56 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += coverflow.h coverflow_p.h
SOURCES += coverflow.cpp main.cpp
