######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 25 07:42:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += linegraph.h
SOURCES += linegraph.cpp main.cpp
