######################################################################
# Automatically generated by qmake (2.01a) Fri May 1 11:54:13 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
QT += network

# Input
HEADERS += src/googleauth.h
SOURCES += src/googleauth.cpp src/main.cpp
