######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 24 21:42:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src/

DEFINES += TEST_GOOGLE_SERVICES

QT += testlib
LIBS += -Wl,-rpath,../../lib -L../../lib -lTHGoogle

# Input
HEADERS += servicestest.h
SOURCES += servicestest.cpp
